format="$all"

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[c]
format = 'via [$name $version]($style)'

[container]
format = '[$symbol \[$name\]]($style) '

[directory]
format = 'in [$path]($style)[$read_only]($read_only_style) '
style = 'cyan bold'
truncation_length = 8
truncation_symbol = 'â€¦/'

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[hostname]
ssh_only = false
format = '@ [$hostname](bold red) [$ssh_symbol](bold blue)'
trim_at = '.nvidia.com'
disabled = false

[shell]
bash_indicator = 'ó±†ƒ'
zsh_indicator = "ó±‰¸"
fish_indicator = 'ó°ˆº'
powershell_indicator = 'îšƒ'
unknown_indicator = 'ï„¨ï„¨'
style = 'cyan bold'
disabled = false

[sudo]
format = '[as root $symbol]($style)'
style = 'bold green'
symbol = 'ï”ª '
disabled = false

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '-5'
time_range = '10:00:00-14:00:00'

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true